// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { Plasmic_12345 } from "./plasmic/test_565656/Plasmic_12345";

function _12345_(props, ref) {
  // Use Plasmic_12345 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic_12345 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all _12345Props here, but feel free
  // to do whatever works for you.
  return <Plasmic_12345 root={{ ref }} {...props} />;
}

const _12345 = React.forwardRef(_12345_);

export default _12345;
