// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eCbx7HJgm8FWkx1AoTEmGN
// Component: Nogt6exAfDZP
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: Zb29Ge7OY3u9/component
import Header002 from "../../Header002"; // plasmic-import: 3GrQwBTmc9Ka/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Ostad from "../../Ostad"; // plasmic-import: GFq5AX6mQYOS/component
import Footer2 from "../../Footer2"; // plasmic-import: BFroENaJU506/component
import { useScreenVariants as useScreenVariantsyOfg4D6YmtF } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: yOfg4d6Ymt_f/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: eCbx7HJgm8FWkx1AoTEmGN/projectcss
import sty from "./Plasmicدورهها.module.css"; // plasmic-import: Nogt6exAfDZP/css
import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: rzUu4x84rFcl/icon
import نقشهراه6PngK5Mx8AnvOm1F from "./images/\u0646\u0642\u0634\u0647\u0631\u0627\u06476Png.png"; // plasmic-import: K5Mx8AnvOM1F/picture
import untitledDesign3Svg6Mzk9YEiw2If from "./images/untitledDesign3Svg.svg"; // plasmic-import: 6Mzk9yEiw2If/picture
import untitledDesign5SvgYgkPia2Qbqv from "./images/untitledDesign5Svg.svg"; // plasmic-import: Ygk-Pia2Qbqv/picture
import untitledDesign4SvgNa7ZLgE9EyZ from "./images/untitledDesign4Svg.svg"; // plasmic-import: na7z-lgE9eyZ/picture
import untitledDesign6SvgP7GCugyFUh4X from "./images/untitledDesign6Svg.svg"; // plasmic-import: p7gCugyFUh4x/picture

createPlasmicElementProxy;

export const Plasmicدورهها__VariantProps = new Array();

export const Plasmicدورهها__ArgProps = new Array();

const $$ = {};

function Plasmicدورهها__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,
        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsyOfg4D6YmtF()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
          dir={"rtl"}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <Header002
            data-plasmic-name={"header002"}
            data-plasmic-override={overrides.header002}
            className={classNames("__wab_instance", sty.header002)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__qiJ01)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__roGyX
              )}
            >
              {"\u062f\u0648\u0631\u0647\u200c\u0647\u0627"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___4FhI1)}>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__kdaGw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__taaCg
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "\u062f\u0648\u0631\u0647 \u0635\u0641\u0631 \u062a\u0627 \u0635\u062f \u0645\u0631\u062d\u0644\u0647 \u06cc\u06a9 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f \u0647\u0648\u0634 \u0645\u0635\u0646\u0648\u0639\u06cc\n"
                      : "\u062f\u0648\u0631\u0647 \u0635\u0641\u0631 \u062a\u0627 \u0635\u062f \u0645\u0631\u062d\u0644\u0647 \u06cc\u06a9 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f \u0647\u0648\u0634 \u0645\u0635\u0646\u0648\u0639\u06cc\n\n"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aMj1Z
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "\u06a9\u0644\u0627\u0633 \u0647\u0627 \u0628\u0647 \u0635\u0648\u0631\u062a \u062a\u062f\u0631\u06cc\u0633 \u0641\u0634\u0631\u062f\u0647 \u0648 \u062d\u0644 \u0633\u0648\u0627\u0644 \u0647\u0633\u062a\u0646\u062f.\n \u062f\u0631 \u0635\u0648\u0631\u062a \u062b\u0628\u062a \u0646\u0627\u0645 \u0641\u06cc\u0644\u0645 \u0636\u0628\u0637 \u0634\u062f\u0647 \u06a9\u0644\u0627\u0633 \u0647\u0627\u06cc \u06af\u0630\u0634\u062a\u0647 \u062f\u0631 \u0627\u062e\u062a\u06cc\u0627\u0631 \u0634\u0645\u0627 \u0642\u0631\u0627\u0631 \u062e\u0648\u0627\u0647\u062f \u06af\u0631\u0641\u062a."
                      : "\u06a9\u0644\u0627\u0633 \u0647\u0627 \u0628\u0647 \u0635\u0648\u0631\u062a \u062a\u062f\u0631\u06cc\u0633 \u0641\u0634\u0631\u062f\u0647 \u0648 \u062d\u0644 \u0633\u0648\u0627\u0644 \u0647\u0633\u062a\u0646\u062f.\n \u062f\u0631 \u0635\u0648\u0631\u062a \u062b\u0628\u062a \u0646\u0627\u0645 \u0641\u06cc\u0644\u0645 \u0636\u0628\u0637 \u0634\u062f\u0647 \u06a9\u0644\u0627\u0633 \u0647\u0627\u06cc \u06af\u0630\u0634\u062a\u0647 \u062f\u0631 \u0627\u062e\u062a\u06cc\u0627\u0631 \u0634\u0645\u0627 \u0642\u0631\u0627\u0631 \u062e\u0648\u0627\u0647\u062f \u06af\u0631\u0641\u062a.\n\n"}
                  </div>
                  <Stack__
                    as={"button"}
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.button
                    )}
                    disabled={false}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToHttpsSurveyPorslineIrSYneDwQv3"] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://survey.porsline.ir/s/YneDwQv3"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                location.assign(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToHttpsSurveyPorslineIrSYneDwQv3"] != null &&
                        typeof $steps["goToHttpsSurveyPorslineIrSYneDwQv3"] ===
                          "object" &&
                        typeof $steps["goToHttpsSurveyPorslineIrSYneDwQv3"]
                          .then === "function"
                      ) {
                        $steps["goToHttpsSurveyPorslineIrSYneDwQv3"] =
                          await $steps["goToHttpsSurveyPorslineIrSYneDwQv3"];
                      }
                    }}
                    title={``}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__ubzWc)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n1C0A
                      )}
                    >
                      {"\u062b\u0628\u062a \u0646\u0627\u0645"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__qii0Q)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__vBdt5)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__c9ZhR)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: نقشهراه6PngK5Mx8AnvOm1F,
                      fullWidth: 1587,
                      fullHeight: 2245,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__wMcBl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hKZH
                )}
              >
                {
                  "\u0627\u0633\u0627\u062a\u06cc\u062f\u06cc \u0627\u0632 \u062f\u0627\u0646\u0634\u06af\u0627\u0647\u200c\u0647\u0627\u06cc \u0628\u0631\u062a\u0631 \u0648 \u0635\u0646\u0639\u062a\u060c \u0647\u0645\u0631\u0627\u0647 \u0634\u0645\u0627 \u062f\u0631 \u0645\u0633\u06cc\u0631 \u067e\u06cc\u0634\u0631\u0641\u062a!\n"
                }
              </div>
              {(() => {
                const child$Props = {
                  arrows: false,
                  autoplay: true,
                  autoplaySpeed: 0.1,
                  beforeChange: async (...eventArgs) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "currentSlide",
                      ["sliderCarousel2", "currentSlide"],
                      SliderWrapper_Helpers
                    ).apply(null, eventArgs);
                  },
                  centerMode: true,
                  centerPadding: "0",
                  className: classNames("__wab_instance", sty.sliderCarousel2),
                  cssEase: "linear",
                  initialSlide: generateStateValueProp($state, [
                    "sliderCarousel2",
                    "currentSlide"
                  ]),
                  ref: ref => {
                    $refs["sliderCarousel2"] = ref;
                  },
                  sliderScopeClassName: sty["sliderCarousel2__slider"],
                  slidesToShow: hasVariant(
                    globalVariants,
                    "screen",
                    "mobileOnly"
                  )
                    ? 2.6
                    : 3.4,
                  speed: 10000
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "currentSlide",
                      plasmicStateName: "sliderCarousel2.currentSlide"
                    }
                  ],

                  [],
                  SliderWrapper_Helpers ?? {},
                  child$Props
                );
                return (
                  <SliderWrapper
                    data-plasmic-name={"sliderCarousel2"}
                    data-plasmic-override={overrides.sliderCarousel2}
                    {...child$Props}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___54WP)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__mgD9N)}
                        displayHeight={"200px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        src={{
                          src: untitledDesign3Svg6Mzk9YEiw2If,
                          fullWidth: 375,
                          fullHeight: 375,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__en6A
                        )}
                      >
                        {
                          "\u06a9\u06cc\u0645\u06cc\u0627 \u0634\u06cc\u062e\u06cc"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nwgg6
                        )}
                      >
                        {
                          "\u06a9\u0627\u0631\u0634\u0646\u0627\u0633\u06cc \u06a9\u0627\u0645\u067e\u06cc\u0648\u062a\u0631 \u062f\u0627\u0646\u0634\u06af\u0627\u0647 \u0627\u0645\u06cc\u0631\u06a9\u0628\u06cc\u0631\n\u0631\u062a\u0628\u0647 20 \u06a9\u0646\u06a9\u0648\u0631 \u0633\u0631\u0627\u0633\u0631\u06cc\n\u0645\u062f\u0631\u0633 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f \u0631\u06cc\u0627\u0636\u06cc \u0648 \u0647\u0648\u0634 \u0645\u0635\u0646\u0648\u0639\u06cc"
                        }
                      </div>
                    </Stack__>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9IheT
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__rU1R6)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        src={{
                          src: untitledDesign5SvgYgkPia2Qbqv,
                          fullWidth: 375,
                          fullHeight: 375,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gVtp3
                        )}
                      >
                        {
                          "\u0645\u062d\u0645\u062f\u062c\u0648\u0627\u062f \u0627\u0633\u0644\u0627\u0645\u06cc \u0628\u06cc\u062f\u06af\u0644\u06cc"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oflYi
                        )}
                      >
                        {
                          "\u06a9\u0627\u0631\u0634\u0646\u0627\u0633\u06cc \u0627\u0631\u0634\u062f \u0627\u0644\u06af\u0648\u0631\u06cc\u062a\u0645 \u0648 \u0645\u062d\u0627\u0633\u0628\u0627\u062a \u062f\u0627\u0646\u0634\u06af\u0627\u0647 \u0634\u0631\u06cc\u0641 \n\u0631\u062a\u0628\u0647 10 \u06a9\u0646\u06a9\u0648\u0631 \u0631\u06cc\u0627\u0636\u06cc \n\u0645\u062f\u0631\u0633 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f \u0631\u06cc\u0627\u0636\u06cc \u0648 \u06a9\u0627\u0645\u067e\u06cc\u0648\u062a\u0631"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rdzTf)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ifZtt)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        src={{
                          src: untitledDesign4SvgNa7ZLgE9EyZ,
                          fullWidth: 375,
                          fullHeight: 375,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__app5B
                        )}
                      >
                        {
                          "\u0645\u062d\u0645\u062f \u0686\u0631\u0627\u063a\u06cc"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Gj1M
                        )}
                      >
                        {
                          "\u06a9\u0627\u0631\u0634\u0646\u0627\u0633\u06cc \u0627\u0631\u0634\u062f \u0647\u0648\u0634 \u0645\u0635\u0646\u0648\u0639\u06cc \u062f\u0627\u0646\u0634\u06af\u0627\u0647 \u0634\u0631\u06cc\u0641 \n\u0645\u062f\u0627\u0644 \u0646\u0642\u0631\u0647 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f \u0631\u06cc\u0627\u0636\u06cc \n\u0631\u062a\u0628\u0647 1 \u06a9\u0646\u06a9\u0648\u0631 \u0645\u0646\u0637\u0642\u0647 3\u064818 \u06a9\u0634\u0648\u0631"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ytXhs)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__z7PJx)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        src={{
                          src: untitledDesign6SvgP7GCugyFUh4X,
                          fullWidth: 375,
                          fullHeight: 375,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3YUhC
                        )}
                      >
                        {
                          "\u0641\u0627\u0637\u0645\u0647 \u0627\u0639\u0638\u0645\u06cc"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y96Pa
                        )}
                      >
                        {
                          "\u06a9\u0627\u0631\u0634\u0646\u0627\u0633\u06cc \u0645\u0647\u0646\u062f\u0633\u06cc \u0628\u0631\u0642 \u062f\u0627\u0646\u0634\u06af\u0627\u0647 \u0634\u0631\u06cc\u0641\n\u0631\u062a\u0628\u0647 69 \u06a9\u0646\u06a9\u0648\u0631 \u0633\u0631\u0627\u0633\u0631\u06cc\n\u0645\u062f\u0631\u0633 \u0631\u06cc\u0627\u0636\u06cc \u06a9\u0646\u06a9\u0648\u0631 \u0648 \u0627\u0644\u0645\u067e\u06cc\u0627\u062f"
                        }
                      </div>
                    </div>
                  </SliderWrapper>
                );
              })()}
            </div>
            <Ostad
              data-plasmic-name={"ostad"}
              data-plasmic-override={overrides.ostad}
              className={classNames("__wab_instance", sty.ostad)}
            />
          </div>
          <Footer2
            data-plasmic-name={"footer2"}
            data-plasmic-override={overrides.footer2}
            className={classNames("__wab_instance", sty.footer2)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header002",
    "columns",
    "button",
    "sliderCarousel2",
    "ostad",
    "footer2"
  ],

  header: ["header"],
  header002: ["header002"],
  columns: ["columns", "button"],
  button: ["button"],
  sliderCarousel2: ["sliderCarousel2"],
  ostad: ["ostad"],
  footer2: ["footer2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicدورهها__ArgProps,
          internalVariantPropNames: Plasmicدورهها__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicدورهها__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u062f\u0648\u0631\u0647\u0647\u0627";
  } else {
    func.displayName = `Plasmicدورهها.${nodeName}`;
  }
  return func;
}

export const Plasmicدورهها = Object.assign(
  // Top-level Plasmicدورهها renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header002: makeNodeComponent("header002"),
    columns: makeNodeComponent("columns"),
    button: makeNodeComponent("button"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    ostad: makeNodeComponent("ostad"),
    footer2: makeNodeComponent("footer2"),
    // Metadata about props expected for Plasmicدورهها
    internalVariantProps: Plasmicدورهها__VariantProps,
    internalArgProps: Plasmicدورهها__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmicدورهها;
/* prettier-ignore-end */
