// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eCbx7HJgm8FWkx1AoTEmGN
// Component: txLEtGVygb7o
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: Zb29Ge7OY3u9/component
import Header002 from "../../Header002"; // plasmic-import: 3GrQwBTmc9Ka/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import Footer2 from "../../Footer2"; // plasmic-import: BFroENaJU506/component
import { useScreenVariants as useScreenVariantsyOfg4D6YmtF } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: yOfg4d6Ymt_f/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: eCbx7HJgm8FWkx1AoTEmGN/projectcss
import sty from "./Plasmicمسابقات.module.css"; // plasmic-import: txLEtGVygb7o/css
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: n0k3Vo5nkTA-/icon
import untitledDesignGif2Yi3DfV6WRpdo from "./images/untitledDesignGif2.gif"; // plasmic-import: yi3dfV6wRpdo/picture

createPlasmicElementProxy;

export const Plasmicمسابقات__VariantProps = new Array();

export const Plasmicمسابقات__ArgProps = new Array();

const $$ = {};

function Plasmicمسابقات__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsyOfg4D6YmtF()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
          dir={"rtl"}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <Header002
            data-plasmic-name={"header002"}
            data-plasmic-override={overrides.header002}
            className={classNames("__wab_instance", sty.header002)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__wo2Y)}>
            <div className={classNames(projectcss.all, sty.freeBox__k86Xn)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mp9Rc)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6TR5F)}
                >
                  <h2
                    data-plasmic-name={"h2"}
                    data-plasmic-override={overrides.h2}
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-bB6hU01n02xa)" }}
                      >
                        {"\u0686\u0627\u0644\u0634"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-Ucj29WEMNFIt)" }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#00D3FF" }}
                      >
                        {
                          "\u06a9\u0627\u0645\u067e\u06cc\u0648\u062a\u0631\u06cc"
                        }
                      </span>
                      <React.Fragment> </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-RkOrJcC26wF-)" }}
                      >
                        {"\u0641\u06a9\u0631 \u06a9\u0646"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-h4UxGY--lzdD)" }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-bB6hU01n02xa)" }}
                      >
                        {"!!"}
                      </span>
                    </React.Fragment>
                  </h2>
                </Stack__>
              </Stack__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___62Xvz)}>
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__dt5FR)}>
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {
                      "\n\u0645\u062c\u0645\u0648\u0639\u0647\u200c\u0627\u06cc \u062c\u0630\u0627\u0628 \u0627\u0632 \u0645\u0639\u0645\u0627\u0647\u0627\u06cc \u062a\u0631\u062c\u0645\u0647 \u0634\u062f\u0647 \u0622\u0632\u0645\u0648\u0646 \u062c\u0647\u0627\u0646\u06cc \u0628\u0628\u0631\u0627\u0633"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__lItvm)}>
                  <PlasmicImg__
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: untitledDesignGif2Yi3DfV6WRpdo,
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___65G0T)}>
              <ChevronDownIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__tx06G)}>
              <Embed
                data-plasmic-name={"embedHtml"}
                data-plasmic-override={overrides.embedHtml}
                className={classNames("__wab_instance", sty.embedHtml)}
                code={
                  "<div id=\"EzzZq8xY\" style=\"min-height: 480px; position: relative;\">\r\n    <div id=\"porsline-loading-EzzZq8xY\" style=\"position: absolute; top: 50%; left: 50%; width: 35px; height: 35px; border: 4px solid rgba(0, 0, 0, 0.1); border-top: 4px solid #555; border-radius: 50%; animation: spin-EzzZq8xY 1s linear infinite;\"></div>\r\n    <script>\r\n      const styleSheet = document.createElement('style');\r\n      styleSheet.innerHTML = `@keyframes spin-EzzZq8xY {\r\n          0% { transform: rotate(0deg); }\r\n          100% { transform: rotate(360deg); }\r\n        }`;\r\n      document.head.appendChild(styleSheet);\r\n      const loadingIndicator = document.getElementById('porsline-loading-EzzZq8xY');\r\n      const script = document.createElement('script');\r\n      script.type = 'text/javascript';\r\n      script.fetchPriority = 'high';\r\n      script.onload = function() {\r\n        loadingIndicator.style.display = 'none';\r\n      };\r\n      script.src = 'https://survey.porsline.ir/embed/eyJ3aWR0aCI6IjEwMCUiLCJoZWlnaHQiOiIxMDAlIiwiYm9yZGVyIjoibm9uZSJ9/EzzZq8xY';\r\n      document.getElementById('EzzZq8xY').appendChild(script);\r\n    </script>\r\n  </div>"
                }
              />
            </div>
          </div>
          <Footer2
            data-plasmic-name={"footer2"}
            data-plasmic-override={overrides.footer2}
            className={classNames("__wab_instance", sty.footer2)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header002",
    "h2",
    "columns",
    "text",
    "img",
    "svg",
    "embedHtml",
    "footer2"
  ],

  header: ["header"],
  header002: ["header002"],
  h2: ["h2"],
  columns: ["columns", "text", "img"],
  text: ["text"],
  img: ["img"],
  svg: ["svg"],
  embedHtml: ["embedHtml"],
  footer2: ["footer2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicمسابقات__ArgProps,
          internalVariantPropNames: Plasmicمسابقات__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicمسابقات__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u0645\u0633\u0627\u0628\u0642\u0627\u062a";
  } else {
    func.displayName = `Plasmicمسابقات.${nodeName}`;
  }
  return func;
}

export const Plasmicمسابقات = Object.assign(
  // Top-level Plasmicمسابقات renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header002: makeNodeComponent("header002"),
    h2: makeNodeComponent("h2"),
    columns: makeNodeComponent("columns"),
    text: makeNodeComponent("text"),
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),
    embedHtml: makeNodeComponent("embedHtml"),
    footer2: makeNodeComponent("footer2"),
    // Metadata about props expected for Plasmicمسابقات
    internalVariantProps: Plasmicمسابقات__VariantProps,
    internalArgProps: Plasmicمسابقات__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmicمسابقات;
/* prettier-ignore-end */
