// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eCbx7HJgm8FWkx1AoTEmGN
// Component: NNClcxYPOSQ9
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Value from "../../Value"; // plasmic-import: 16IIeWFEMbUD/component
import Button from "../../Button"; // plasmic-import: 5wVC3rQb102V/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: eCbx7HJgm8FWkx1AoTEmGN/projectcss
import sty from "./PlasmicEmojiValueProps.module.css"; // plasmic-import: NNClcxYPOSQ9/css
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: J3fi-AkS9d9s/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: J95z-KxkyUDA/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: P_2Mkm88GnZb/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: b5GdtlVpd2OO/icon

createPlasmicElementProxy;

export const PlasmicEmojiValueProps__VariantProps = new Array();

export const PlasmicEmojiValueProps__ArgProps = new Array("children");

const $$ = {};

function PlasmicEmojiValueProps__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___4WqSv)}
          >
            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button___15Fga)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__skEjz)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  size={"large"}
                  submitsForm={true}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__wl33I)}
              icon={
                <PlaneIcon
                  className={classNames(projectcss.all, sty.svg__yvx6Y)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vTWjU
                )}
              >
                {"Worldwide shipping"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iKf4
                )}
              >
                {"Special financing and earn rewards."}
              </div>
            </Value>
            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button__d2Cjc)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg___3KKx)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  size={"large"}
                  submitsForm={true}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__qSKm)}
              icon={
                <DocumentIcon
                  className={classNames(projectcss.all, sty.svg__ydHkp)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h1WBx
                )}
              >
                {"30-day guarantee"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zCD
                )}
              >
                {"Free return policy."}
              </div>
            </Value>
            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button__uwhcl)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__r7Old)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  size={"large"}
                  submitsForm={true}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__nFspi)}
              icon={
                <LockIcon
                  className={classNames(projectcss.all, sty.svg__eqytn)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yBof6
                )}
              >
                {"Secured payments"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rDjPg
                )}
              >
                {"We accept major credit cards."}
              </div>
            </Value>
          </Stack__>
        ),

        value: args.children
      })}
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEmojiValueProps__ArgProps,
          internalVariantPropNames: PlasmicEmojiValueProps__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEmojiValueProps__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEmojiValueProps";
  } else {
    func.displayName = `PlasmicEmojiValueProps.${nodeName}`;
  }
  return func;
}

export const PlasmicEmojiValueProps = Object.assign(
  // Top-level PlasmicEmojiValueProps renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicEmojiValueProps
    internalVariantProps: PlasmicEmojiValueProps__VariantProps,
    internalArgProps: PlasmicEmojiValueProps__ArgProps
  }
);

export default PlasmicEmojiValueProps;
/* prettier-ignore-end */
